### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/docs-md#2]
- [ ] Class constructor
- [ ] Class constructor public properties
- [ ] Create a link for `@see` and `@link`
- [ ] What to do with re-exports, e.g. https://github.com/timdeschryver/docs-md/blob/master/docs/angular-testing-library/testing-library/query-by-text.md
- [ ] Remove `@ignore` and `@internal` from the docs
- [ ] Sort sections in markdown
